### PR TITLE
Add line-numbers base on a metalsmith option

### PR DESCRIPTION
**Pull request by cedric-legallo**
Hello,
I find this prism plugin(line-numbers) mandatory so it would be a nice add to metalsmith prism plugin.

Best Regards !

### CODE REVIEW

**Comment by robmcguinness** [comment]
@cedric-legallo I noticed that the lib doesn't require a parent container in order for it to work.  Would it be fair to add the css class to the `<code>` block directly if a parent `<pre>` container is not available?

**Ex 1:**
```javascript
<code class="language-javascript line-numbers">
var name = "Rob";
</code>
```

**Ex 2:**
```javascript
<pre class="line-numbers">
 <code class="language-javascript ">
  var name = "Rob";
 </code>
</pre>
```

I am thinking the code should be:

```javascript
if (options.lineNumbers) {
  var $parent = $this.parent();
  $parent && $parent.is('pre') ? $parent.addClass('line-numbers') : $el.addClass('line-numbers');
}
```

thoughts? should a parent `<pre>` container be enforced?

**Comment by robmcguinness** [comment]
you can check out https://github.com/Availity/metalsmith-prism/commit/ed4fbe75a52604ef715c4433dbd62ad9fcb9c3b8 and review so that I can cut a release asap.

**Comment by robmcguinness** [comment]
actually i don't think line-number can be attached to anything other than `<pre>` tags [prism-line-numbers.css#L1](https://github.com/PrismJS/prism/blob/4303c940d3d3a20e8ce7635bf23331c75060f5c5/plugins/line-numbers/prism-line-numbers.css#L1)

**Comment by cedric-legallo** [comment]
Prism.js put a <pre> tag for all multiline code templates (which is where
line-numbers makes sense)
For monoline code, there is just a <code> tag and you are right, we should
not add the class for this cases (even if it does nothing it pollutes HTML
templates)

something like taht i suppose :
if ($parent && $parent.is('pre')) {
  $parent.addClass('line-numbers');
}

and no else J

On Fri, Mar 18, 2016 at 6:49 PM, robert mcguinness <notifications@github.com

**Comment by robmcguinness** [comment]
Should be released on NPM.  Let me know if there are any issues.  Thanks for your contribution!

* [index.js#L69](https://github.com/Availity/metalsmith-prism/blob/master/lib/index.js#L69)
* [index.js#L42](https://github.com/Availity/metalsmith-prism/blob/master/lib/index.js#L42)

**Comment by cedric-legallo** [comment]
Tested, it works.
Still not as powerful as using prism directly, but i cant write markdown
using prism :D (html in markdown is meh)

it fulfill perfectly my needs, i can delete my fork.
Thank You for the reactivity.

On Sat, Mar 19, 2016 at 5:05 PM, robert mcguinness <notifications@github.com

**Comment by clarle** [comment]
Hey there!

I originally thought that this feature would generate the line numbers for me (without any browser-side JavaScript), but after reading more closely, it only adds the classname `line-numbers`.

I forked `metalsmith-prism` to [@clarle/metalsmith-prism](https://github.com/clarle/metalsmith-prism) in case someone needed the actual line numbers to be generated from Metalsmith.

It's kind of a quick and dirty hack - see https://github.com/clarle/metalsmith-prism/commit/f8739fd6177b2c237c864e47bacf5c41f7e47b69 for how it works, but it does work.  I published it under `@clarle/metalsmith-prism` in case anyone else needs it.

Cheers!

**Comment by cedric-legallo** [comment]
Hi,

Prism adds the line-numbers (require the adequate plugin in prism.js)

**Comment by clarle** [comment]
@cedric-legallo My problem was that I can't include Prism on the client - I'm building an AMP page where no additional browser-side JavaScript can be included.

Prism's line-numbers plugin only works in the browser, and not in Node, so I needed to work around it.

**Comment by robmcguinness** [comment]
I'm wondering if it's possible to use the native plugin from within Node.

**Comment by walkerrandolphsmith** [comment]
@clarle You don't need metalsmith-prism, cherrio, or lodash at all. You can get this functionality with just metalsmith-markdown.  

```js
var markdown = require('metalsmith-markdown');
var marked = require('marked');

const renderer = new marked.Renderer();

renderer.code = function(code, lang, escaped) {
    code = this.options.highlight(code, lang);
    const classes = ` class="${this.options.langPrefix}${language} line-numbers"`;
    return `<pre${classes}><code${classes}>${code}</code></pre>`
};

const highlighter = (code, lang) => {
    if (!prism.languages.hasOwnProperty(lang)) {
        lang = extensions[lang] || 'markup';
    }
    const highlightedCode = prism.highlight(code, prism.languages[lang]);

    const numberOfLines = code.split('\n').length;
    const lines = Array
                    .from(Array(numberOfLines), (_, i) => i)
                    .map(() => '<span></span>')
                    .join('');
    const $lineNumbersRows = `<span class="line-numbers-rows">${lines}</span>`;

    return highlightedCode + $lineNumbersRows;
};

...
.use(markdown({
            gfm: true,
            smartypants: true,
            renderer: renderer,
            langPrefix: 'language-',
            highlight: highlighter
        }))
...
```

**Pull request merged**
