### PR TITLE
Support syntax highlighting for all languages Prism supports

### PR DESCRIPTION
**Pull request by eliotsykes**

### CODE REVIEW

**Comment by eliotsykes** [comment]
Feedback welcome and I'm happy to squash the commits if this is acceptable.

**Comment by robmcguinness** [comment]
thank you! there was a small issue requiring the additional syntax plugins with Node.  The fix was applied https://github.com/Availity/metalsmith-prism/commit/b93719aa6efec302d28e65bef6b7f661965e3868.  Please let me know if everything is working as expected.

**Comment by eliotsykes** [comment]
And thanks to you @robmcguinness for incorporating the changes and making them better so quick! I just tried 1.1.0 on my site and its working fine, the syntax highlighting for Ruby & Bash looks perfect.

**Comment by robmcguinness** [comment]
:+1:

**Pull request merged**
